language: go
sudo: false

os:
  - linux

# - osx

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

install:
 - go get -t ./...
 - '[[ `go version` =~ go1.[0-4][^0-9] ]] || go get -u github.com/kisielk/errcheck'
 - go get -u golang.org/x/tools/cmd/goimports
 - '[[ `go version` =~ go1.[0-4][^0-9] ]] || go get -u github.com/golang/lint/golint'

script:
  - make check
  - go test ./...
  - go test -cpu=2 -race ./...
