language: go
sudo: false

os:
  - linux

# - osx

go:
  - 1.3.3
  - 1.4.2
  - 1.5.1

# - tip

install:
 - go get ./...
 - go get -u golang.org/x/tools/cmd/goimports
 - go get -u github.com/golang/lint/golint

script:
  - make check
  - go test -v ./...
  - go test -cpu=2 -race -v ./...
