name: rclone
version: 1.35
summary: rsync for cloud storage
description:
  Rclone is a command line program to sync files to and from cloud storage providers such as
  Google Drive, Amazon Drive, S3, Dropbox, Backblaze B2, One Drive, Swift, Hubic, Cloudfiles, Google Cloud Storage, Yandex Files.
confinement: strict
grade: stable

apps:
  rclone:
    command: bin/rclone
    plugs: [home, network, network-bind,fuse-support]

parts:
  rclone:
    plugin: go
    source: https://github.com/ncw/rclone
    source-tag: v1.35
    source-type: git
    go-importpath: github.com/ncw/rclone
    build-packages: [gcc, libgudev-1.0-dev,fuse]
