---
version: 2

jobs:

  build:
    machine: true

    working_directory: ~/.go_workspace/src/github.com/rclone/rclone

    steps:
    - checkout

    - run:
        name: Cross-compile rclone
        command: |
            docker pull billziss/xgo-cgofuse
            go get -v github.com/karalabe/xgo
            xgo \
                -image=billziss/xgo-cgofuse \
                -targets=darwin/386,darwin/amd64,linux/386,linux/amd64,windows/386,windows/amd64 \
                -tags cmount \
                -dest build \
                .
            xgo \
                -image=billziss/xgo-cgofuse \
                -targets=android/*,ios/* \
                -dest build \
                .

    - run:
        name: Build rclone
        command: |
            docker pull golang
            docker run --rm -v "$PWD":/usr/src/rclone -w /usr/src/rclone golang go build -mod=vendor -v

    - run:
        name: Upload artifacts
        command: |
          make circleci_upload

    - store_artifacts:
        path: build
