tests:
 - path: backend
   addbackend: true
   nobinary:   true
   short:      true
 - path: fs/operations
   fastlist: true
 - path: fs/sync
   fastlist: true
 - path: vfs
 - path: cmd/serve/restic
   localonly: true
backends:
 # - backend:  "amazonclouddrive"
 #   remote:   "TestAmazonCloudDrive:"
 #   fastlist: false
 - backend:  "local"
   remote:   ""
   fastlist: false
 - backend:  "b2"
   remote:   "TestB2:"
   fastlist: true
 - backend:  "crypt"
   remote:   "TestCryptDrive:"
   fastlist: true
 - backend:  "crypt"
   remote:   "TestCryptSwift:"
   fastlist: false
 - backend:  "drive"
   remote:   "TestDrive:"
   fastlist: true
 - backend:  "dropbox"
   remote:   "TestDropbox:"
   fastlist: false
 - backend:  "googlecloudstorage"
   remote:   "TestGoogleCloudStorage:"
   fastlist: true
 - backend:  "googlephotos"
   remote:   "TestGooglePhotos:"
   tests:
     - backend
 - backend:  "hubic"
   remote:   "TestHubic:"
   fastlist: false
 - backend:  "jottacloud"
   remote:   "TestJottacloud:"
   fastlist: true
 - backend:  "onedrive"
   remote:   "TestOneDrive:"
   fastlist: false
 - backend:  "s3"
   remote:   "TestS3:"
   fastlist: true
 - backend:  "s3"
   remote:   "TestS3Minio:"
   fastlist: true
   ignore:
     - TestIntegration/FsMkdir/FsPutFiles/SetTier
 - backend:  "s3"
   remote:   "TestS3Wasabi:"
   fastlist: true
 - backend:  "s3"
   remote:   "TestS3DigitalOcean:"
   fastlist: true
   ignore:
     - TestIntegration/FsMkdir/FsPutFiles/FsCopy
     - TestIntegration/FsMkdir/FsPutFiles/SetTier
 - backend:  "s3"
   remote:   "TestS3Ceph:"
   fastlist: true
   ignore:
     - TestIntegration/FsMkdir/FsPutFiles/FsCopy
     - TestIntegration/FsMkdir/FsPutFiles/SetTier
 - backend:  "s3"
   remote:   "TestS3Alibaba:"
   fastlist: true
 - backend:  "sftp"
   remote:   "TestSftp:"
   fastlist: false
 - backend:  "swift"
   remote:   "TestSwift:"
   fastlist: true
 - backend:  "swift"
   remote:   "TestSwiftCeph:"
   fastlist: true
   ignore:
     - TestIntegration/FsMkdir/FsPutFiles/FsCopy
 - backend:  "yandex"
   remote:   "TestYandex:"
   fastlist: false
 - backend:  "ftp"
   remote:   "TestFTP:"
   fastlist: false
 - backend:  "box"
   remote:   "TestBox:"
   fastlist: false
 - backend:  "fichier"
   remote:   "TestFichier:"
   fastlist: false
 - backend:  "qingstor"
   remote:   "TestQingStor:"
   fastlist: false
   oneonly:  true
 - backend:  "azureblob"
   remote:   "TestAzureBlob:"
   fastlist: true
 - backend:  "pcloud"
   remote:   "TestPcloud:"
   fastlist: false
 - backend:  "webdav"
   remote:   "TestWebdav:"
   fastlist: false
 - backend:  "cache"
   remote:   "TestCache:"
   fastlist: false
 - backend:  "mega"
   remote:   "TestMega:"
   fastlist: false
   ignore:
     - TestIntegration/FsMkdir/FsPutFiles/PublicLink
     - TestDirRename
 - backend:  "opendrive"
   remote:   "TestOpenDrive:"
   fastlist: false
 - backend:  "union"
   remote:   "TestUnion:"
   fastlist: false
 - backend:  "koofr"
   remote:   "TestKoofr:"
   fastlist: false
 - backend:  "premiumizeme"
   remote:   "TestPremiumizeMe:"
   fastlist: false
 - backend:  "putio"
   remote:   "TestPutio:"
   subdir:   false
   fastlist: false
 - backend:  "mailru"
   remote:   "TestMailru:"
   subdir:   false
   fastlist: false
